version: '3'

services: 
  debian_py3_opencv:
    build: .
    environment:
      DISPLAY: 172.17.0.1:0
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - ~:/thr_main
    network_mode: "bridge"
    command: /bin/bash