# enable color support of ls and also add handy aliasesif [ -x /usr/bin/dircolors ]; then
alias ls='ls --color=auto -G -h'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'fi

# some more ls aliases
alias lsa="ls -alF"
alias ls1="ls -1"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# turn off shell history copying
alias solo='unset PROMPT_COMMAND'

# User specific aliases and functions
alias remake="make clean && make -j4 && make install"
alias remaked="make clean && make debug && make install"
alias psf='ps -ef | grep $1'
alias Top='top -ocpu -O+rsize -n 30'
alias check_so="nm -d"

alias cds='cd ~/src'

# cnt
alias cda="cd $MII_HOME/src/auxil"
alias cdx="cd $MII_HOME/src/xfd"
alias cdg="cd $MII_HOME/src/gui200"
alias cdw="cd $MII_WKSP"

